USE master;
GO

IF NOT EXISTS (SELECT 1 FROM sys.availability_groups WHERE name = N'SQLSentinelAON')
BEGIN
    ALTER AVAILABILITY GROUP [SQLSentinelAON] JOIN WITH (CLUSTER_TYPE = NONE);
END
GO

ALTER AVAILABILITY GROUP [SQLSentinelAON] GRANT CREATE ANY DATABASE;
GO
